apiVersion: v1
kind: ServiceAccount
metadata:
  name: pandax
  labels:
    app.kubernetes.io/name: pandax
---
kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: pandax-rolebinding
  labels:
    app.kubernetes.io/name: pandax
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: cluster-admin
subjects:
- kind: ServiceAccount
  name: pandax
